# Generated by Django 3.0.6 on 2020-05-13 08:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app_0', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='player',
            options={'default_related_name': 'players'},
        ),
        migrations.AddField(
            model_name='authuser',
            name='is_staff',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='player',
            name='ipl_team',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='players', to='app_0.IPLTeam'),
        ),
    ]
