# Generated by Django 3.0.6 on 2020-05-13 11:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_0', '0002_auto_20200513_0809'),
    ]

    operations = [
        migrations.AddField(
            model_name='iplteam',
            name='description',
            field=models.TextField(default=' '),
            preserve_default=False,
        ),
    ]
