# Generated by Django 3.0.6 on 2020-05-13 14:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app_0', '0003_iplteam_description'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='player',
            name='is_team_active',
        ),
        migrations.AlterField(
            model_name='player',
            name='ipl_team',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='players', to='app_0.IPLTeam'),
        ),
    ]
