# Generated by Django 3.0.6 on 2020-05-17 13:50

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app_0', '0005_auto_20200517_1212'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='team',
            options={'default_related_name': 'teams'},
        ),
        migrations.AlterField(
            model_name='team',
            name='created_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='teams', to=settings.AUTH_USER_MODEL),
        ),
    ]
