# Generated by Django 3.0.6 on 2020-05-18 04:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_0', '0008_auto_20200517_2030'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='authuser',
            name='points',
        ),
        migrations.AddField(
            model_name='team',
            name='set_caption',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='team',
            name='set_power_player',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='team',
            name='set_vise_caption',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='teamplayermappings',
            name='is_caption',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='teamplayermappings',
            name='is_power_player',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='teamplayermappings',
            name='is_vise_caption',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='teamplayermappings',
            name='points',
            field=models.IntegerField(default=0),
        ),
    ]
