# Generated by Django 3.0.6 on 2020-05-17 17:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('app_0', '0008_auto_20200517_2030'),
    ]

    operations = [
        migrations.CreateModel(
            name='Match',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(auto_now=True)),
                ('cover', models.ImageField(upload_to='mach_covers/')),
                ('team_1', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='team_2', to='app_0.IPLTeam')),
                ('team_2', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='team_1', to='app_0.IPLTeam')),
            ],
            options={
                'default_related_name': 'matches',
            },
        ),
        migrations.CreateModel(
            name='MatchPlayerMapping',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('score', models.IntegerField(default=0)),
                ('match', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='match_player_mappings', to='admin_1.Match')),
                ('player', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='match_player_mappings', to='app_0.Player')),
            ],
            options={
                'default_related_name': 'match_player_mappings',
            },
        ),
    ]
